### ISSUE TITLE
Cannot find "DayZ_x64.exe"

### ISSUE THREAD

**Issue by ClarkieUK** [CypherMediaGIT/DayZCOMode-Livonia-Edition#1]
When launching the batch I get an error message that goes as follows, 

_Windows cannot find "DayZ_x64.exe". Make sure you've typed the name correctly, then try again._ 

I believed this to be an issue with the directory so had a little dig around but found nothing, so I've resolved to coming here and asking for help. Does anyone have any ideas?

**Comment by CypherMediaGIT** [comment]
Are you using Livonia Edition this version, or the original Chernarus version of CommunityOfflineMode?

**Comment by ClarkieUK** [comment]
The Livonia

**Comment by CypherMediaGIT** [comment]
Ok in the DayZ folder where the Mission folder is what .exe files are in that folder that start with DayZ?

**Comment by ClarkieUK** [comment]
I managed to resolve the issue :D , I had simple moved the folder into the wrong area by mistake and added an extra step to the directory, thank you very much for offering your help tho :)

**Comment by CypherMediaGIT** [comment]
No Problem, I’m happy you sorted it out, enjoy Livonia and don’t hesitate to come back if you have any other issues.
