### ISSUE TITLE
Mods not loading in single-player mission

### ISSUE THREAD

**Issue by Sci-fer** [CypherMediaGIT/DayZCOMode-Livonia-Edition#3]
I can't load any mods on the single-player mission. I load the game through the .bat file with the following parameters:
```
@echo off

taskkill /F /IM DayZ_x64.exe /T

RD /s /q "storage_-1" > nul 2>&1

cd ../../

start DayZ_x64.exe -nosplash -noPause -noBenchmark -filePatching -doLogs -scriptDebug=true^
 -mission=.\Missions\DayZCommunityOfflineMode.Enoch^
 -mod=@CJ187-ImmersiveMap;@WalkingDeadZombies
```
However, when I leave the mission and the game goes back to the home screen, it shows that the mods are all loaded, but only Livonia has a green ball next to it.
Please help me.

**Comment by Sci-fer** [comment]
I was wondering if this is happening because those are server mods not client mods. I can't tell the difference by the way.

**Comment by CypherMediaGIT** [comment]
Any server mods do not need to be loaded via the command line in the .bat files, currently though offline mode does have issues loading mods due to extensive changes made in the base DayZ Game on the 1.08 Update .. a fix is being worked on

**Comment by Sci-fer** [comment]
@CypherMediaGIT Thank you so much!
